## Pandas Crash Course (Part 4)

### Understanding GroupBy objects

In [1]:
import pandas as pd

In [2]:
titanic = pd.read_csv("titanic.csv")

In [3]:
titanic.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked deck
0         0       3    male  22.0      1      0   7.2500        S  NaN
1         1       1  female  38.0      1      0  71.2833        C    C
2         1       3  female  26.0      0      0   7.9250        S  NaN
3         1       1  female  35.0      1      0  53.1000        S    C
4         0       3    male  35.0      0      0   8.0500        S  NaN

In [4]:
titanic.tail()

     survived  pclass     sex   age  sibsp  parch   fare embarked deck
886         0       2    male  27.0      0      0  13.00        S  NaN
887         1       1  female  19.0      0      0  30.00        S    B
888         0       3  female   NaN      1      2  23.45        S  NaN
889         1       1    male  26.0      0      0  30.00        C    C
890         0       3    male  32.0      0      0   7.75        Q  NaN

In [ ]:
titanic.info()

In [ ]:
titanic_slice = titanic.iloc[:10, [2,3]]

In [ ]:
titanic_slice

In [ ]:
titanic_slice.groupby("sex")

In [ ]:
gbo = titanic_slice.groupby("sex")

In [ ]:
type(gbo)

In [ ]:
gbo.groups

In [ ]:
l = list(gbo)

In [ ]:
l

In [ ]:
len(l)

In [ ]:
l[0]

In [ ]:
type(l[0])

In [ ]:
l[0][0]

In [ ]:
l[0][1]

In [ ]:
type(l[0][1])

In [ ]:
l[1]

In [ ]:
titanic_slice.loc[titanic_slice.sex == "female"]

In [ ]:
titanic_slice_f = titanic_slice.loc[titanic_slice.sex == "female"]
titanic_slice_f

In [ ]:
titanic_slice_m = titanic_slice.loc[titanic_slice.sex == "male"]
titanic_slice_m

In [ ]:
titanic_slice_f.equals(l[0][1])

In [ ]:
for element in gbo:
    print(element[1])

### Splitting with many Keys

In [ ]:
import pandas as pd

In [ ]:
summer = pd.read_csv("summer.csv")

In [ ]:
summer.head()

In [ ]:
summer.info()

In [ ]:
summer.Country.nunique()

In [ ]:
split1 = summer.groupby("Country")

In [ ]:
l = list(split1)
l

In [ ]:
len(l)

In [ ]:
l[100][1]

In [ ]:
split2 = summer.groupby(by = ["Country", "Gender"])

In [ ]:
l2 = list(split2)
l2

In [ ]:
len(l2)

In [ ]:
l2[104]

In [ ]:
l2[104][0]

In [ ]:
l2[104][1]

### split-apply-combine explained

In [ ]:
import pandas as pd

In [ ]:
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic_slice = titanic.iloc[:10, [2,3]]

In [ ]:
titanic_slice

In [ ]:
list(titanic_slice.groupby("sex"))[0][1]

In [ ]:
list(titanic_slice.groupby("sex"))[1][1]

In [ ]:
titanic_slice.groupby("sex").mean()

In [ ]:
titanic.groupby("sex").survived.sum()

In [ ]:
titanic.groupby("sex")[["fare", "age"]].max()

In [ ]:
new_df = titanic.groupby("sex").mean(numeric_only = True)

In [ ]:
new_df

In [ ]:
import matplotlib.pyplot as plt
plt.style.use("seaborn-v0_8")

In [ ]:
new_df.plot(kind = "bar", subplots = True, figsize = (8,15), fontsize = 13)
plt.show()

### split-apply-combine applied

In [ ]:
import pandas as pd

In [ ]:
summer = pd.read_csv("summer.csv")

In [ ]:
summer.head()

In [ ]:
summer.info()

In [ ]:
medals_per_country = summer.groupby("Country").Medal.count().nlargest(n = 20)
medals_per_country

In [ ]:
import matplotlib.pyplot as plt
plt.style.use("seaborn-v0_8")

In [ ]:
medals_per_country.plot(kind = "bar", figsize = (14, 8), fontsize = 14)
plt.xlabel("Country", fontsize = 13)
plt.ylabel("No. of Medals", fontsize = 13)
plt.title("Summer Olympic Games (Total Medals per Country)", fontsize = 16)
plt.show()

In [ ]:
titanic = pd.read_csv("titanic.csv")

In [ ]:
titanic.head()

In [ ]:
titanic.info()

In [ ]:
titanic.describe()

In [ ]:
titanic.fare.mean()

In [ ]:
titanic.groupby("pclass").fare.mean()

In [ ]:
titanic.survived.sum()

In [ ]:
titanic.survived.mean()

In [ ]:
titanic.groupby("sex").survived.mean()

In [ ]:
titanic.groupby("pclass").survived.mean()

In [ ]:
titanic["ad_chi"] = "adult"

In [ ]:
titanic.loc[titanic.age < 18, "ad_chi"] = "child"

In [ ]:
titanic.head(20)

In [ ]:
titanic.ad_chi.value_counts()

In [ ]:
titanic.groupby("ad_chi").survived.mean()

In [ ]:
titanic.groupby(["sex", "ad_chi"]).survived.count()

In [ ]:
titanic.groupby(["sex", "ad_chi"]).survived.mean().sort_values(ascending = False)

In [ ]:
w_and_c_first = titanic.groupby(["sex", "ad_chi"]).survived.mean().sort_values(ascending = False)

In [ ]:
w_and_c_first.plot(kind = "bar", figsize = (14,8), fontsize = 14)
plt.xlabel("Groups", fontsize = 13)
plt.ylabel("Survival Rate", fontsize = 13)
plt.title("Titanic Survival Rate by Sex/Age-Groups", fontsize = 16)
plt.show()